In [14]:
import numpy as np
bbb = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])
print(bbb)
print (type(bbb))
ghgh = bbb.tolist()
print(ghgh)
print(type(ghgh))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>


In [16]:
import numpy as np
              
gfg = np.matrix([[1, 2, 3], [4, 5, 6],[7,8,9]])
              
geek = gfg.trace()
    
print(geek)

[[15]]


In [23]:
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])
print("Original array: ")
print(x)
print("Values bigger than 5 =", x[x>5])
print("Values smaller than 5 =", x[x<5])


Original array: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Values bigger than 5 = [6 7 8 9]
Values smaller than 5 = [1 2 3 4]


In [33]:
import numpy as np
  
A = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])
B = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])

C = np.add(A,B ) 
print ("C : ", C) 

C :  [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [49]:
import numpy as np

arr = [20, 2, 7, 1, 34]
print(arr)
print("arr : ", arr) 
print("mean of arr : ", np.mean(arr))
print("",arr- np.mean(arr))

[20, 2, 7, 1, 34]
arr :  [20, 2, 7, 1, 34]
mean of arr :  12.8
 [  7.2 -10.8  -5.8 -11.8  21.2]
